name: GitHub Actions Build and Deploy Hexo

on:
  push:
    branches:
      - espory

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: espory
          
      - name: Setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Hexo Generate
        run: |
          rm -f .yarnclean
          yarn --frozen-lockfile --ignore-engines --ignore-optional --non-interactive --silent --ignore-scripts --production=false
          rm -rf ./public
          yarn run hexo clean
          yarn run hexo generate

      - name: Hexo Deploy
        env:
          SSH_PRIVATE: ${{ secrets.HEXO_SSH_PRIVATE }}
          GIT_USER: espory
          GIT_EMAIL: bwyang20@fudan.edu.cn
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "$GIT_USER"
          git config --global user.email "$GIT_EMAIL"
          yarn run hexo deploy